# Installed for linting the project
language: node_js
node_js: "6"

notifications:
  email:
    on_success: never
    on_failure: change

script: 'curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh'

# Needed to disable the auto-install step running `npm install`
install: true

git:
  depth: 10

sudo: false

os:
  - linux
  - osx

env:
  global:
    - APM_TEST_PACKAGES="underscore.string underscore-plus"
    - ATOM_LINT_WITH_BUNDLED_NODE="false"

  matrix:
    - ATOM_CHANNEL=stable
    - ATOM_CHANNEL=beta

addons:
  apt:
    packages:
    - build-essential
    - git
    - libgnome-keyring-dev
    - fakeroot

branches:
  only:
    - master
